public enum BIRDTYPE {
    HAWKS, EAGLES, OSPREY,

    EMUS, KIWIS, MOAS,

    OWLS,

    PARROTS, ROSE_RING_PARAKEET, GRAY_PARROT, SULFUR_CRESTED_COCKATOO,

    PIGEONS, DOVES,

    SHOREBIRDS, GREAT_AUK, HORNED_PUFFIN, AFRICAN_JACANA,

    WATERFOWL, DUCKS, SWANS, GEESE
}
